apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app }}
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app:  {{ .Values.app }}
  template:
    metadata:
      labels:
        app:  {{ .Values.app }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ .Release.Name }}
        volumeMounts:
        - name: {{ .Values.volumes.name }}
          mountPath: {{ .Values.volumes.mountPath }}
        livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            httpGet:
                path: {{ .Values.livenessProbe.httpGet.path }}
                port: {{ .Values.livenessProbe.httpGet.port }}
      volumes:
      - name: {{ .Values.volumes.name }}
        persistentVolumeClaim:
           claimName: {{ .Values.persistence.name }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodeSelector.hostname}}